Initial commit & generate scraper
preditock/preditock-core pull request #1
Opened 2024-01-04 14:32 UTC by iovsomnium

2024-01-04 14:47 UTC, Nam-SW commented on src/main.py
main.py 에 실행하는 내용이 들어감.
본 예제에선 save_news_to_db("[기업명]", 1, 400) 을 기업별로 쫙 실행하는게 들어감

2024-01-04 14:48 UTC, Nam-SW commented on batch/scraper_batch.py
> +save_news_to_db("삼성전자", 1, 400)
단순 테스트코드면 다음 블럭 안에서 실행하기
```py
if __name__ == "__main__":
    pass  # 실행코드
```
해당 파일을 `python 파일명.py`로 직접 실행했을때만 실행됨

2024-01-04 14:50 UTC, Nam-SW commented on batch/scraper_batch.py
> +    news_list = crawl_news(company, page_start, page_end)
체인으로 연결되는건 지양하는게 좋을듯.

```py
def func1(a):
    return r

def func2(r):
    pass

r = func1(1)
func2(r)
```

2024-01-04 14:58 UTC, Nam-SW commented on config/conf.py
> +News = namedtuple('News', ['search_company', 'write_date', 'title', 'content', 'url', 'img_url', 'publisher', 'keyword', 'summary', 'user_id'])
dataclass 로 타입까지 명시해서 작성하는게 이뻐보임

```py
@dataclass
class News:
    search_company: str
    write_date: str
    title: str
    content: str
    url: str
    img_url: Optional[str] = None
    publisher: str
    keyword: List[str]
    summary: str
    user_id: Union[str, int] 
```

2024-01-04 15:18 UTC, Nam-SW commented on db_handler/db_handler.py
> +        pass
상속 안하면 그냥 에러 터트리기
```py
raise raise NotImplementedError("에러")
```

2024-01-04 15:47 UTC, Nam-SW requested changes
일해라 코드싸개야

2024-01-04 15:47 UTC, Nam-SW commented on requirements.txt
> +beautifulsoup4
버전 붙이는게 좋음

2024-01-04 15:47 UTC, Nam-SW commented on scraper/scraper.py
> +            url = "https://search.naver.com/search.naver?where=news&sm=tab_pge&query=" + search + "&sort=1&start=" + str(page)
formatting 사용하기
```py
url = ㄹ"https://search.naver.com/search.naver?where=news&sm=tab_pge&query={search}&sort=1&start={page}"
```

2024-01-04 15:47 UTC, Nam-SW commented on scraper/scraper.py
> +        attrs_content = []
리스트 컴프리헨션

```py
attrs_content = [art.attrs[attrs] for art in articles]
```

2024-01-04 15:47 UTC, Nam-SW commented on scraper/scraper.py
> +        for i in content:
네이밍 제대로 하기
i랑 j가 뭔데

2024-01-04 15:47 UTC, Nam-SW commented on scraper/scraper.py
> +        self.makeList(news_url_1, news_url)
makeList 데이터 반환하는데 어따갖다버림
call by reference여도 명시하기

2024-01-04 15:47 UTC, Nam-SW commented on scraper/scraper.py
> +    def makePgNum(self, num: int) -> int:
함수는 스네이크 케이스

2024-01-04 15:47 UTC, Nam-SW commented on db_handler/db_handler.py
> +    def get_news_by_id(self, news_id):
타이핑

2024-01-04 15:47 UTC, Nam-SW commented on db_handler/db_handler.py
> +        self.cursor.execute(query, values)
object 하나를 괄호로 감싸면 아무 의미가 없음. 그냥 산수연산에서 괄호로 들어감.
튜플로 설정하려면 쉼표 넣어주기
```py
self.cursor.execute(query, (values, ))
```

2024-01-04 15:47 UTC, Nam-SW commented on db_handler/db_handler.py
> +        self.cursor.execute(query, values)
executemany 검색해보기

2024-01-04 15:47 UTC, Nam-SW commented on scraper/scraper.py
> +            if span is not None and span.img is not None:
예외처리 프로세스 확인 필요

2024-01-04 15:47 UTC, Nam-SW commented on scraper/scraper.py
> +            news_date = re.sub(pattern='<[^>]*>', repl='', string=str(news_date))
정규식 패턴 객체를 따로 만들어서 self 변수로 만들어놔도 좋을듯
re.sub, re.find 등으로 바로 접근하면 그때그때 패턴 객체를 새로 만들어서 엄청 약간이지만 손실 발생함

2024-01-04 15:47 UTC, Nam-SW commented on scraper/scraper.py
> +            news_date = '0000-00-00 00:00:00'
굳이 저렇게 할바에 db에 null 로 넣어주는게 처리하기 편하지 않을까 하는 의견

2024-01-04 15:47 UTC, Nam-SW commented on scraper/scraper.py
> +        pattern1 = '<[^>]*>'
이런 패턴들 모아다가 생성자에서 self 변수로 만들어두는게 좋을 것 같음

2024-01-05 14:14 UTC, iovsomnium commented on scraper/scraper.py
> +            url = "https://search.naver.com/search.naver?where=news&sm=tab_pge&query=" + search + "&sort=1&start=" + str(page)
f를 ㄹ로 해둔건 너무 개대충이고

2024-01-05 15:44 UTC, iovsomnium commented on scraper/scraper.py
> +            news_date = '0000-00-00 00:00:00'
not null로 박아둬서 그러긴 한데 사실 원래는 저런 케이스가 나오면 안되긴 하는 거라 일단은 변경 안하고 둠

2024-01-05 16:07 UTC, iovsomnium commented on requirements.txt
> +beautifulsoup4
전체 조사 이후 다시 추가 예정

2024-01-05 16:07 UTC, iovsomnium commented on scraper/scraper.py
> +        for i in content:
비중 문제라 생각해서 일단은 보류 나중에 다시 수정하도록

2024-01-05 16:07 UTC, iovsomnium commented on batch/scraper_batch.py
> +    news_list = crawl_news(company, page_start, page_end)
이부분은 scraper 전체 한번 갈면서 수정함

2024-01-05 16:21 UTC, Nam-SW approved these changes

2024-01-06 05:58 UTC, merged